//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  oeuvres: Oeuvres;
  oeuvresConnection: OeuvresConnection;
  site: Site;
  siteConnection: SiteConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryOeuvresArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryOeuvresConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<OeuvresFilter>;
};


export type QuerySiteArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteFilter>;
};

export type DocumentFilter = {
  oeuvres?: InputMaybe<OeuvresFilter>;
  site?: InputMaybe<SiteFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Oeuvres | Site | Folder;

export type OeuvresImages = {
  __typename?: 'OeuvresImages';
  image?: Maybe<Scalars['String']['output']>;
};

export type Oeuvres = Node & Document & {
  __typename?: 'Oeuvres';
  titre: Scalars['String']['output'];
  annee?: Maybe<Scalars['Float']['output']>;
  technique?: Maybe<Scalars['String']['output']>;
  largeur_cm?: Maybe<Scalars['Float']['output']>;
  hauteur_cm?: Maybe<Scalars['Float']['output']>;
  prix?: Maybe<Scalars['Float']['output']>;
  statut?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  ordre?: Maybe<Scalars['Float']['output']>;
  images?: Maybe<Array<Maybe<OeuvresImages>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type OeuvresImagesFilter = {
  image?: InputMaybe<ImageFilter>;
};

export type OeuvresFilter = {
  titre?: InputMaybe<StringFilter>;
  annee?: InputMaybe<NumberFilter>;
  technique?: InputMaybe<StringFilter>;
  largeur_cm?: InputMaybe<NumberFilter>;
  hauteur_cm?: InputMaybe<NumberFilter>;
  prix?: InputMaybe<NumberFilter>;
  statut?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  ordre?: InputMaybe<NumberFilter>;
  images?: InputMaybe<OeuvresImagesFilter>;
};

export type OeuvresConnectionEdges = {
  __typename?: 'OeuvresConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Oeuvres>;
};

export type OeuvresConnection = Connection & {
  __typename?: 'OeuvresConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<OeuvresConnectionEdges>>>;
};

export type Site = Node & Document & {
  __typename?: 'Site';
  nom_artiste?: Maybe<Scalars['String']['output']>;
  accroche?: Maybe<Scalars['String']['output']>;
  hero_titre?: Maybe<Scalars['String']['output']>;
  hero_sous_titre?: Maybe<Scalars['String']['output']>;
  hero_image?: Maybe<Scalars['String']['output']>;
  a_propos_titre?: Maybe<Scalars['String']['output']>;
  a_propos_texte?: Maybe<Scalars['String']['output']>;
  a_propos_image?: Maybe<Scalars['String']['output']>;
  philosophie_titre?: Maybe<Scalars['String']['output']>;
  philosophie_texte?: Maybe<Scalars['String']['output']>;
  email_contact?: Maybe<Scalars['String']['output']>;
  telephone?: Maybe<Scalars['String']['output']>;
  ville_atelier?: Maybe<Scalars['String']['output']>;
  instagram?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SiteFilter = {
  nom_artiste?: InputMaybe<StringFilter>;
  accroche?: InputMaybe<StringFilter>;
  hero_titre?: InputMaybe<StringFilter>;
  hero_sous_titre?: InputMaybe<StringFilter>;
  hero_image?: InputMaybe<ImageFilter>;
  a_propos_titre?: InputMaybe<StringFilter>;
  a_propos_texte?: InputMaybe<StringFilter>;
  a_propos_image?: InputMaybe<ImageFilter>;
  philosophie_titre?: InputMaybe<StringFilter>;
  philosophie_texte?: InputMaybe<StringFilter>;
  email_contact?: InputMaybe<StringFilter>;
  telephone?: InputMaybe<StringFilter>;
  ville_atelier?: InputMaybe<StringFilter>;
  instagram?: InputMaybe<StringFilter>;
};

export type SiteConnectionEdges = {
  __typename?: 'SiteConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Site>;
};

export type SiteConnection = Connection & {
  __typename?: 'SiteConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateOeuvres: Oeuvres;
  createOeuvres: Oeuvres;
  updateSite: Site;
  createSite: Site;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateOeuvresArgs = {
  relativePath: Scalars['String']['input'];
  params: OeuvresMutation;
};


export type MutationCreateOeuvresArgs = {
  relativePath: Scalars['String']['input'];
  params: OeuvresMutation;
};


export type MutationUpdateSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteMutation;
};


export type MutationCreateSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteMutation;
};

export type DocumentUpdateMutation = {
  oeuvres?: InputMaybe<OeuvresMutation>;
  site?: InputMaybe<SiteMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  oeuvres?: InputMaybe<OeuvresMutation>;
  site?: InputMaybe<SiteMutation>;
};

export type OeuvresImagesMutation = {
  image?: InputMaybe<Scalars['String']['input']>;
};

export type OeuvresMutation = {
  titre?: InputMaybe<Scalars['String']['input']>;
  annee?: InputMaybe<Scalars['Float']['input']>;
  technique?: InputMaybe<Scalars['String']['input']>;
  largeur_cm?: InputMaybe<Scalars['Float']['input']>;
  hauteur_cm?: InputMaybe<Scalars['Float']['input']>;
  prix?: InputMaybe<Scalars['Float']['input']>;
  statut?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  ordre?: InputMaybe<Scalars['Float']['input']>;
  images?: InputMaybe<Array<InputMaybe<OeuvresImagesMutation>>>;
};

export type SiteMutation = {
  nom_artiste?: InputMaybe<Scalars['String']['input']>;
  accroche?: InputMaybe<Scalars['String']['input']>;
  hero_titre?: InputMaybe<Scalars['String']['input']>;
  hero_sous_titre?: InputMaybe<Scalars['String']['input']>;
  hero_image?: InputMaybe<Scalars['String']['input']>;
  a_propos_titre?: InputMaybe<Scalars['String']['input']>;
  a_propos_texte?: InputMaybe<Scalars['String']['input']>;
  a_propos_image?: InputMaybe<Scalars['String']['input']>;
  philosophie_titre?: InputMaybe<Scalars['String']['input']>;
  philosophie_texte?: InputMaybe<Scalars['String']['input']>;
  email_contact?: InputMaybe<Scalars['String']['input']>;
  telephone?: InputMaybe<Scalars['String']['input']>;
  ville_atelier?: InputMaybe<Scalars['String']['input']>;
  instagram?: InputMaybe<Scalars['String']['input']>;
};

export type OeuvresPartsFragment = { __typename: 'Oeuvres', titre: string, annee?: number | null, technique?: string | null, largeur_cm?: number | null, hauteur_cm?: number | null, prix?: number | null, statut?: string | null, description?: string | null, ordre?: number | null, images?: Array<{ __typename: 'OeuvresImages', image?: string | null } | null> | null };

export type SitePartsFragment = { __typename: 'Site', nom_artiste?: string | null, accroche?: string | null, hero_titre?: string | null, hero_sous_titre?: string | null, hero_image?: string | null, a_propos_titre?: string | null, a_propos_texte?: string | null, a_propos_image?: string | null, philosophie_titre?: string | null, philosophie_texte?: string | null, email_contact?: string | null, telephone?: string | null, ville_atelier?: string | null, instagram?: string | null };

export type OeuvresQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type OeuvresQuery = { __typename?: 'Query', oeuvres: { __typename: 'Oeuvres', id: string, titre: string, annee?: number | null, technique?: string | null, largeur_cm?: number | null, hauteur_cm?: number | null, prix?: number | null, statut?: string | null, description?: string | null, ordre?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, images?: Array<{ __typename: 'OeuvresImages', image?: string | null } | null> | null } };

export type OeuvresConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<OeuvresFilter>;
}>;


export type OeuvresConnectionQuery = { __typename?: 'Query', oeuvresConnection: { __typename?: 'OeuvresConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'OeuvresConnectionEdges', cursor: string, node?: { __typename: 'Oeuvres', id: string, titre: string, annee?: number | null, technique?: string | null, largeur_cm?: number | null, hauteur_cm?: number | null, prix?: number | null, statut?: string | null, description?: string | null, ordre?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, images?: Array<{ __typename: 'OeuvresImages', image?: string | null } | null> | null } | null } | null> | null } };

export type SiteQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SiteQuery = { __typename?: 'Query', site: { __typename: 'Site', id: string, nom_artiste?: string | null, accroche?: string | null, hero_titre?: string | null, hero_sous_titre?: string | null, hero_image?: string | null, a_propos_titre?: string | null, a_propos_texte?: string | null, a_propos_image?: string | null, philosophie_titre?: string | null, philosophie_texte?: string | null, email_contact?: string | null, telephone?: string | null, ville_atelier?: string | null, instagram?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SiteConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteFilter>;
}>;


export type SiteConnectionQuery = { __typename?: 'Query', siteConnection: { __typename?: 'SiteConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SiteConnectionEdges', cursor: string, node?: { __typename: 'Site', id: string, nom_artiste?: string | null, accroche?: string | null, hero_titre?: string | null, hero_sous_titre?: string | null, hero_image?: string | null, a_propos_titre?: string | null, a_propos_texte?: string | null, a_propos_image?: string | null, philosophie_titre?: string | null, philosophie_texte?: string | null, email_contact?: string | null, telephone?: string | null, ville_atelier?: string | null, instagram?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const OeuvresPartsFragmentDoc = gql`
    fragment OeuvresParts on Oeuvres {
  __typename
  titre
  annee
  technique
  largeur_cm
  hauteur_cm
  prix
  statut
  description
  ordre
  images {
    __typename
    image
  }
}
    `;
export const SitePartsFragmentDoc = gql`
    fragment SiteParts on Site {
  __typename
  nom_artiste
  accroche
  hero_titre
  hero_sous_titre
  hero_image
  a_propos_titre
  a_propos_texte
  a_propos_image
  philosophie_titre
  philosophie_texte
  email_contact
  telephone
  ville_atelier
  instagram
}
    `;
export const OeuvresDocument = gql`
    query oeuvres($relativePath: String!) {
  oeuvres(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...OeuvresParts
  }
}
    ${OeuvresPartsFragmentDoc}`;
export const OeuvresConnectionDocument = gql`
    query oeuvresConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: OeuvresFilter) {
  oeuvresConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...OeuvresParts
      }
    }
  }
}
    ${OeuvresPartsFragmentDoc}`;
export const SiteDocument = gql`
    query site($relativePath: String!) {
  site(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteParts
  }
}
    ${SitePartsFragmentDoc}`;
export const SiteConnectionDocument = gql`
    query siteConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteFilter) {
  siteConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteParts
      }
    }
  }
}
    ${SitePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      oeuvres(variables: OeuvresQueryVariables, options?: C): Promise<{data: OeuvresQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OeuvresQueryVariables, query: string}> {
        return requester<{data: OeuvresQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OeuvresQueryVariables, query: string}, OeuvresQueryVariables>(OeuvresDocument, variables, options);
      },
    oeuvresConnection(variables?: OeuvresConnectionQueryVariables, options?: C): Promise<{data: OeuvresConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OeuvresConnectionQueryVariables, query: string}> {
        return requester<{data: OeuvresConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OeuvresConnectionQueryVariables, query: string}, OeuvresConnectionQueryVariables>(OeuvresConnectionDocument, variables, options);
      },
    site(variables: SiteQueryVariables, options?: C): Promise<{data: SiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteQueryVariables, query: string}> {
        return requester<{data: SiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteQueryVariables, query: string}, SiteQueryVariables>(SiteDocument, variables, options);
      },
    siteConnection(variables?: SiteConnectionQueryVariables, options?: C): Promise<{data: SiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConnectionQueryVariables, query: string}> {
        return requester<{data: SiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConnectionQueryVariables, query: string}, SiteConnectionQueryVariables>(SiteConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  